version: '3.8'

services:
  app:
    build: .
    container_name: shopease-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopease
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: shopease-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopease
    ports:
      - "3307:3306"